include:
  - project: claranet/guildes/pipeline/helpers
    ref: v4.0.0
    file: tool_versions.yml
  - project: "claranet/smartinfra/tooling/projects/templates/golang"
    file: "/gitlab-ci.yml"

variables:
  PROXY_ADDRESS: http://10.195.1.23:3128/
  KUBERNETES_CPU_REQUEST: "1"
  KUBERNETES_MEMORY_LIMIT: "2Gi"
  KUBERNETES_MEMORY_REQUEST: "2Gi"
  ftp_proxy: "${PROXY_ADDRESS}"
  FTP_PROXY: "${PROXY_ADDRESS}"
  http_proxy: "${PROXY_ADDRESS}"
  HTTP_PROXY: "${PROXY_ADDRESS}"
  https_proxy: "${PROXY_ADDRESS}"
  HTTPS_PROXY: "${PROXY_ADDRESS}"
  no_proxy: "localhost,127.0.0.0/8"
  NO_PROXY: "localhost,127.0.0.0/8"

stages:
  - build
  - publish
  - docs
  - prepare
  - release

default:
  tags:
    - tool-renovate
    - clara-cloud
    - healthcare

.build_image: &build_image
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  needs:
    - tool versions
  script:
    - if [ -z "$CI_COMMIT_TAG" ]; then export IMAGE_TAG=$CI_COMMIT_SHORT_SHA; else export IMAGE_TAG=$CI_COMMIT_TAG; fi
    - DESTINATION="${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${IMAGE_TAG}"
    - echo $DESTINATION
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/$DOCKERFILE
      --destination $DESTINATION
      --build-arg GOLANG_VERSION=1.21
      --build-arg "ftp_proxy=${ftp_proxy}"
      --build-arg "FTP_PROXY=${ftp_proxy}"
      --build-arg "http_proxy=${http_proxy}"
      --build-arg "HTTP_PROXY=${http_proxy}"
      --build-arg "https_proxy=${https_proxy}"
      --build-arg "HTTPS_PROXY=${https_proxy}"
      --build-arg "no_proxy=${no_proxy}"
      --build-arg "NO_PROXY=${no_proxy}"
      --build-arg "TARGETARCH=amd64"
      --build-arg "TARGETOS=linux"
      $ADDITIONAL_KANIKO_FLAG
    - echo "Successfully pushed image to ${DESTINATION}"

Build Operator:
  <<: *build_image
  variables:
    DOCKERFILE: Dockerfile
    IMAGE_NAME: squid-operator


# Documentation build job
# This job builds the MkDocs documentation and publishes it as an artifact
docs:
  stage: docs
  image: python:3.11-slim
  script:
    - pip install -r requirements.txt
    # Build documentation
    - mkdocs build
  artifacts:
    paths:
      - site/
    expire_in: 1 week
  only:
    - main
    - tags

# GitLab Pages deployment job
Pages:
  stage: docs
  image: python:3.11-slim
  needs:
    - docs # This job depends on the Build Documentation job
  script:
    - mkdir -p public
    - cp -r site/* public/  # GitLab Pages serves from the "public" directory
  artifacts:
    paths:
      - public
  only:
    - main   # Deploy only from the main branch
    - tags   # Deploy only from tags


prepare_job:
  stage: prepare
  image: alpine:latest
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+$/'
  script:
    - apk add curl jq
    - 'curl -H "PRIVATE-TOKEN: $CI_API_TOKEN" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/repository/changelog?version=$CI_COMMIT_TAG" | jq -r .notes > release_notes.md'
    - 'curl -H "PRIVATE-TOKEN: $CI_API_TOKEN" -X POST "$CI_API_V4_URL/projects/$CI_PROJECT_ID/repository/changelog?version=$CI_COMMIT_TAG"'
  artifacts:
    paths:
      - release_notes.md

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: prepare_job
      artifacts: true
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+$/'
  script:
    - echo "Creating release"
  release:
    name: "Release $CI_COMMIT_TAG"
    description: release_notes.md
    tag_name: "$CI_COMMIT_TAG"
    ref: "$CI_COMMIT_SHA"
    assets:
      links:
        - name: "Container Image $CI_COMMIT_TAG"
          url: "https://$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA"
