include:
  - project: claranet/guildes/pipeline/helpers
    ref: v4.0.0
    file: tool_versions.yml
  - project: "claranet/smartinfra/tooling/projects/templates/golang"
    file: "/gitlab-ci.yml"

golangci:
  extends:
    - .golangci_lint

go_test:
  extends:
    - .go_test

go_deps:
  extends:
    - .go_deps

variables:
  PROXY_ADDRESS: http://10.195.1.23:3128/
  KUBERNETES_CPU_REQUEST: "1"
  KUBERNETES_MEMORY_LIMIT: "2Gi"
  KUBERNETES_MEMORY_REQUEST: "2Gi"
  ftp_proxy: "${PROXY_ADDRESS}"
  FTP_PROXY: "${PROXY_ADDRESS}"
  http_proxy: "${PROXY_ADDRESS}"
  HTTP_PROXY: "${PROXY_ADDRESS}"
  https_proxy: "${PROXY_ADDRESS}"
  HTTPS_PROXY: "${PROXY_ADDRESS}"
  no_proxy: "localhost,127.0.0.0/8"
  NO_PROXY: "localhost,127.0.0.0/8"

stages:
  - build
  - test
  - publish

default:
  tags:
    - prj-internal-only
    - healthcare

.build_image: &build_image
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  needs:
    - tool versions
  script:
    - DESTINATION="${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"
    - echo $DESTINATION
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/$DOCKERFILE
      --destination $DESTINATION
      --build-arg GOLANG_VERSION=1.21
      --build-arg "ftp_proxy=${ftp_proxy}"
      --build-arg "FTP_PROXY=${ftp_proxy}"
      --build-arg "http_proxy=${http_proxy}"
      --build-arg "HTTP_PROXY=${http_proxy}"
      --build-arg "https_proxy=${https_proxy}"
      --build-arg "HTTPS_PROXY=${https_proxy}"
      --build-arg "no_proxy=${no_proxy}"
      --build-arg "NO_PROXY=${no_proxy}"
      --build-arg "TARGETARCH=amd64"
      --build-arg "TARGETOS=linux"
      $ADDITIONAL_KANIKO_FLAG
    - echo "Successfully pushed image to ${DESTINATION}"

Build Operator:
  <<: *build_image
  variables:
    DOCKERFILE: Dockerfile
    IMAGE_NAME: squid-operator
