default_install_hook_types: [commit-msg, pre-commit]
# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-case-conflict
      - id: check-yaml
        exclude: ^deploy/
        args:
          - --unsafe
      - id: check-symlinks
      - id: check-added-large-files
      - id: detect-private-key

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.1.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [] # optional: list of Conventional Commits types to allow e.g. [feat, fix, ci, chore, test]

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.0
    hooks:
      - id: go-fmt
      - id: go-imports
      - id: no-go-testing
      # - id: golangci-lint
      # - id: go-unit-tests

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.0.9
    hooks:
    - id: helmlint
