---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-squid-cdk-clara-net-v1-squidconfigs
  failurePolicy: Fail
  name: msquidconfigs.kb.io
  rules:
  - apiGroups:
    - squid.cdk.clara.net
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - squidconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-squid-cdk-clara-net-v1-squidinstance
  failurePolicy: Fail
  name: msquidinstance.kb.io
  rules:
  - apiGroups:
    - squid.cdk.clara.net
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - squidinstances
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-squid-cdk-clara-net-v1-squidconfigs
  failurePolicy: Fail
  name: vsquidconfigs.kb.io
  rules:
  - apiGroups:
    - squid.cdk.clara.net
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - squidconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-squid-cdk-clara-net-v1-squidinstance
  failurePolicy: Fail
  name: vsquidinstance.kb.io
  rules:
  - apiGroups:
    - squid.cdk.clara.net
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - squidinstances
  sideEffects: None
