---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - squid.cdk.clara.net
  resources:
  - configs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - squid.cdk.clara.net
  resources:
  - configs/finalizers
  verbs:
  - update
- apiGroups:
  - squid.cdk.clara.net
  resources:
  - configs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - squid.cdk.clara.net
  resources:
  - rules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - squid.cdk.clara.net
  resources:
  - rules/finalizers
  verbs:
  - update
- apiGroups:
  - squid.cdk.clara.net
  resources:
  - rules/status
  verbs:
  - get
  - patch
  - update
