apiVersion: squid.cdk.clara.net/v1
kind: Configs
metadata:
  labels:
    app.kubernetes.io/name: squid-operator
    app.kubernetes.io/managed-by: kustomize
  name: configs-sample
spec:
  # TODO(user): Add fields here
