apiVersion: squid.cdk.clara.net/v1
kind: Configs
metadata:
  labels:
    app.kubernetes.io/name: squid-operator
    app.kubernetes.io/managed-by: kustomize
  name: internal-squid
  namespace: claranet-system
spec:
  replicas: 2
  ingress: {}
  hpa: {}
  image:
    tag: 5.2-22.04_beta
    repository: ubuntu/squid
  squidConfig: |
    #Network config
    visible_hostname squid.adm.grita.fr
    http_port 0.0.0.0:3128
    hosts_file /etc/hosts
    dns_v4_first on

    coredump_dir /var/spool/squid

    ftp_passive on
    ftp_sanitycheck on
    forwarded_for off

    #Disable cache
    cache deny ALL

    access_log /var/log/squid/access.log combined
    #esante syslog server
    access_log syslog:10.195.195.15 squid
