apiVersion: squid.cdk.clara.net/v1
kind: Rules
metadata:
  labels:
    app.kubernetes.io/name: squid-operator
    app.kubernetes.io/managed-by: kustomize
  name: rules-first
  namespace: claranet-system
spec:
  name: infra
  squidConfigRef:
    name: internal-squid
  rules: |
    # INFRA RULES
    acl INFRA src 10.34.12.1
    acl src_port port 443
---
# apiVersion: squid.cdk.clara.net/v1
# kind: Rules
# metadata:
#   labels:
#     app.kubernetes.io/name: squid-operator
#     app.kubernetes.io/managed-by: kustomize
#   name: rules-sample-next
#   namespace: claranet-system
# spec:
#   name: infra
#   squidConfigRef:
#     name: internal-squid-next
#   rules: |
#     # INFRA RULES
#     acl INFRA src 10.34.12.2
#     acl dst_port port 443
---
apiVersion: squid.cdk.clara.net/v1
kind: Rules
metadata:
  labels:
    app.kubernetes.io/name: squid-operator
    app.kubernetes.io/managed-by: kustomize
  name: rules-next
  namespace: claranet-system
spec:
  name: infraTwo
  squidConfigRef:
    name: internal-squid
  rules: |
    # NEXT INFRA RULES
    acl INFRA src 10.34.12.2
    acl tricks_port port 443
# ---
# apiVersion: squid.cdk.clara.net/v1
# kind: Rules
# metadata:
#   labels:
#     app.kubernetes.io/name: squid-operator
#     app.kubernetes.io/managed-by: kustomize
#   name: rules-duplicate-two
#   namespace: claranet-system
# spec:
#   name: infraTestDuplicate
#   squidConfigRef:
#     name: internal-squid
#   rules: |
#     # NEXT INFRA RULES
#     acl INFRA src 10.34.12.2
#     acl tricks_port port 443
