# permissions for end users to edit squidinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "squid-operator.fullname" . }}-squidinstance-editor-role
  labels:
    {{- include "squid-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - squid.cdk.clara.net
  resources:
  - squidinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - squid.cdk.clara.net
  resources:
  - squidinstances/status
  verbs:
  - get
